### ISSUE TITLE
Expand network attributes of the Host model

### ISSUE THREAD

**Issue by fdupont-redhat** [konveyor/forklift-controller#120]
When a vSphere provider is added, the UI leverages the inventory to list the hosts and allow selecting a migration network.
By default, the migration traffic will go over the management network, but the UI cannot display that information. However, the vSphere API exposes the IP address of the ESXi host used for management:

`MOR:HostSystem.summary.managementServerIp`.

If the inventory contained that attribute, the UI could then identify the default network used for migration, by doing some IP calculation based on the IP addresses and netmasks of the pNICs. The netmask is available as:

`MOR:HostSystem.configManager.networkSystem.networkInfo.vnic[*].spec.ip.subnetMask`

**Comment by mturley** [comment]
Related UI issue: https://github.com/konveyor/forklift-ui/issues/292

**Comment by mturley** [comment]
This is now blocking PR https://github.com/konveyor/forklift-ui/pull/427 (to fix https://github.com/konveyor/forklift-ui/issues/421 and https://github.com/konveyor/forklift-ui/issues/292, both BZs targeted for GA). cc @jortel
