### ISSUE TITLE
Add authentication to Inventory service

### ISSUE THREAD

**Issue by fdupont-redhat** [konveyor/forklift-controller#165]
The provider inventory contains information about the provider layout and this can be considered sensitive by some users.

It would be better to add an authentication layer to the inventory service to limit access to authenticated users. The UI impersonates the logged in user and can then access the inventory.

RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1929140

**Comment by jortel** [comment]
For GA, let's just do a `TokenReview` for authentication and defer authorization.

**Comment by jortel** [comment]
Done. https://github.com/konveyor/forklift-controller/pull/203
