### ISSUE TITLE
Allow using names instead of ids in plans and mappings

### ISSUE THREAD

**Issue by fdupont-redhat** [konveyor/forklift-controller#70]
When a user creates a CR for a plan or a mapping, the VMware networks, storages, VMs... are referenced by id. The UI displays names, then translates them to ids when creating the CRs. However, for a user that would like to interact only with the API, finding these IDs is not trivial, as they are not displayed in the vCenter UI.

Then comes the uniqueness issue of names. so it would require providing additional information when using names:

- VM name is unique withing the folder where it is located. So, the unique key is the absolute path of the VM.
- Datastore scope the datacenter. So, the unique key is the combination of datacenter name and datastore name.
- Standard vSphere Network scope is the host. Given that the VM belong to only one host, the unique key is the network name.
- Distributed vSwitch scope is the datacenter. So, the unique key is the combination of datacenter name and network name. This way, if the datacenter is provided we can expect the network to be a Distributed vSwitch.

**Comment by jortel** [comment]
Seems that `name` is not unique across _standard_ and _DVPortGroup_.  One option is to include `type` (standard|dvportgroup) in the source network specification.

**Comment by fdupont-redhat** [comment]
But, if you provide the Datacenter name with the Network name, you can assume that it's a DVPortGroup:

- Standard: `"name": "my_std_net"
- DVPortGroup: "name": "my_dc/my_dvp_net"

This is the kind of strings we discussed where the controller checks the a regex to identify the type, instead of using a type field.

**Comment by jortel** [comment]
The mapping on a plan is cluster scoped (not host scoped) so I think the name would still need to be qualified.
Also, aren't standard networks DC scoped (not host)?
